import type {Config} from "tailwindcss";
import daisyui from "daisyui"
import animate from "tailwindcss-animate"
import catppuccin from '@catppuccin/daisyui'

const config: Config = {
    darkMode: ["class"],
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    plugins: [
        daisyui,
        animate
    ],
    daisyui: {
        themes: ["light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset", {
                rosepine: {
                    "primary": "#c4a7e7",
                    "secondary": "#ebbcba",
                    "accent": "#f6c177",
                    "neutral": "#191724",
                    "base-100": "#1f1d2e",
                    "info": "#31748f",
                    "success": "#9ccfd8",
                    "warning": "#f6c177",
                    "error": "#eb6f92",
                },
                'rosepine-moon': {
                    "primary": "#c4a7e7",
                    "secondary": "#ea9a97",
                    "accent": "#c4a7e7",
                    "neutral": "#2a273f",
                    "base-100": "#232136",
                    "info": "#3e8fb0",
                    "success": "#9ccfd8",
                    "warning": "#f6c177",
                    "error": "#eb6f92",
                },
                'rosepine-dawn': {
                    "primary": "#907aa9",
                    "secondary": "#d7827e",
                    "accent": "#907aa9",
                    "neutral": "#faf4ed",
                    "base-100": "#fffaf3",
                    "info": "#286983",
                    "success": "#56949f",
                    "warning": "#ea9d34",
                    "error": "#b4637a",
                },
            },
            catppuccin('latte'),
            catppuccin('frappe'),
            catppuccin('macchiato'),
            catppuccin('mocha'),
        ],
    },
};
export default config;