import {PrismaClient} from '@prisma/client';
const prisma = new PrismaClient();

const countries = [
  { "code": "DZ", "name": "Algeria", "color": "#008000" },
  { "code": "AO", "name": "Angola", "color": "#FF0000" },
  { "code": "BJ", "name": "Benin", "color": "#008000" },
  { "code": "BW", "name": "Botswana", "color": "#76ACDC" },
  { "code": "BF", "name": "Burkina Faso", "color": "#FF0000" },
  { "code": "BI", "name": "Burundi", "color": "#FF0000" },
  { "code": "CM", "name": "Cameroon", "color": "#008000" },
  { "code": "CV", "name": "Cape Verde", "color": "#0000FF" },
  { "code": "CF", "name": "Central African Republic", "color": "#0000FF" },
  { "code": "TD", "name": "Chad", "color": "#00008B" },
  { "code": "KM", "name": "Comoros", "color": "#FFFF00" },
  {
    "code": "CD",
    "name": "Congo, Democratic Republic of the",
    "color": "#007FFF"
  },
  { "code": "CG", "name": "Congo, Republic of the", "color": "#008000" },
  { "code": "DJ", "name": "Djibouti", "color": "#75AADB" },
  { "code": "EG", "name": "Egypt", "color": "#FF0000" },
  { "code": "GQ", "name": "Equatorial Guinea", "color": "#008000" },
  { "code": "ER", "name": "Eritrea", "color": "#008000" },
  { "code": "SZ", "name": "Eswatini", "color": "#3C5EBA" },
  { "code": "ET", "name": "Ethiopia", "color": "#008000" },
  { "code": "GA", "name": "Gabon", "color": "#008000" },
  { "code": "GM", "name": "Gambia", "color": "#FF0000" },
  { "code": "GH", "name": "Ghana", "color": "#FF0000" },
  { "code": "GN", "name": "Guinea", "color": "#FF0000" },
  { "code": "GW", "name": "Guinea-Bissau", "color": "#FF0000" },
  { "code": "CI", "name": "Ivory Coast", "color": "#FFA500" },
  { "code": "KE", "name": "Kenya", "color": "#000000" },
  { "code": "LS", "name": "Lesotho", "color": "#00008B" },
  { "code": "LR", "name": "Liberia", "color": "#FF0000" },
  { "code": "LY", "name": "Libya", "color": "#FF0000" },
  { "code": "MG", "name": "Madagascar", "color": "#FC3B2E" },
  { "code": "MW", "name": "Malawi", "color": "#000000" },
  { "code": "ML", "name": "Mali", "color": "#008000" },
  { "code": "MR", "name": "Mauritania", "color": "#008000" },
  { "code": "MU", "name": "Mauritius", "color": "#FF0000" },
  { "code": "MA", "name": "Morocco", "color": "#C22229" },
  { "code": "MZ", "name": "Mozambique", "color": "#008000" },
  { "code": "NA", "name": "Namibia", "color": "#0000FF" },
  { "code": "NE", "name": "Niger", "color": "#E05206" },
  { "code": "NG", "name": "Nigeria", "color": "#008000" },
  { "code": "RW", "name": "Rwanda", "color": "#00A3DF" },
  {
    "code": "ST",
    "name": "S\u00c3\u00a3o Tom\u00c3\u00a9 and Pr\u00c3\u00adncipe",
    "color": "#12AD2B"
  },
  { "code": "SN", "name": "Senegal", "color": "#008000" },
  { "code": "SC", "name": "Seychelles", "color": "#0000FF" },
  { "code": "SL", "name": "Sierra Leone", "color": "#008000" },
  { "code": "SO", "name": "Somalia", "color": "#007FFF" },
  { "code": "ZA", "name": "South Africa", "color": "#FF0000" },
  { "code": "SS", "name": "South Sudan", "color": "#000000" },
  { "code": "SD", "name": "Sudan", "color": "#FF0000" },
  { "code": "TZ", "name": "Tanzania", "color": "#008000" },
  { "code": "TG", "name": "Togo", "color": "#008000" },
  { "code": "TN", "name": "Tunisia", "color": "#FF0000" },
  { "code": "UG", "name": "Uganda", "color": "#000000" },
  { "code": "ZM", "name": "Zambia", "color": "#008000" },
  { "code": "ZW", "name": "Zimbabwe", "color": "#008000" },
  { "code": "AI", "name": "Anguilla", "color": "#FF861F" },
  { "code": "AG", "name": "Antigua and Barbuda", "color": "#FF0000" },
  { "code": "AW", "name": "Aruba", "color": "#FBE870" },
  { "code": "BS", "name": "Bahamas", "color": "#40E0D0" },
  { "code": "BB", "name": "Barbados", "color": "#00008B" },
  { "code": "BZ", "name": "Belize", "color": "#0066CC" },
  { "code": "BM", "name": "Bermuda", "color": "#ED0A3F" },
  { "code": "VG", "name": "British Virgin Islands", "color": "#29AB87" },
  { "code": "CA", "name": "Canada", "color": "#FF0000" },
  { "code": "KY", "name": "Cayman Islands", "color": "#3F26BF" },
  { "code": "CR", "name": "Costa Rica", "color": "#0000FF" },
  { "code": "CU", "name": "Cuba", "color": "#0000FF" },
  { "code": "CW", "name": "Cura\u00c3\u00a7ao", "color": "#0000FF" },
  { "code": "DM", "name": "Dominica", "color": "#008000" },
  { "code": "DO", "name": "Dominican Republic", "color": "#0000FF" },
  { "code": "SV", "name": "El Salvador", "color": "#0000FF" },
  { "code": "GD", "name": "Grenada", "color": "#01A368" },
  { "code": "GP", "name": "Guadeloupe", "color": "#01A368" },
  { "code": "GT", "name": "Guatemala", "color": "#0066FF" },
  { "code": "HT", "name": "Haiti", "color": "#0000FF" },
  { "code": "HN", "name": "Honduras", "color": "#0000FF" },
  { "code": "JM", "name": "Jamaica", "color": "#008000" },
  { "code": "MQ", "name": "Martinique", "color": "#FFFFFF" },
  { "code": "MX", "name": "Mexico", "color": "#008000" },
  { "code": "MS", "name": "Montserrat", "color": "#000000" },
  { "code": "NI", "name": "Nicaragua", "color": "#0000FF" },
  { "code": "PA", "name": "Panama", "color": "#0000FF" },
  { "code": "PR", "name": "Puerto Rico", "color": "#FF0000" },
  { "code": "KN", "name": "Saint Kitts and Nevis", "color": "#008000" },
  { "code": "LC", "name": "Saint Lucia", "color": "#50BFE6" },
  { "code": "MF", "name": "Saint Martin", "color": "#FFFF00" },
  { "code": "PM", "name": "Saint Pierre et Miquelon", "color": "#0000FF" },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "color": "#2243B6"
  },
  { "code": "SX", "name": "Sint Maarten", "color": "#ED0A3F" },
  { "code": "TT", "name": "Trinidad and Tobago", "color": "#FF0000" },
  { "code": "TC", "name": "Turks and Caicos", "color": "#436CB9" },
  { "code": "US", "name": "United States of America", "color": "#FF0000" },
  { "code": "VI", "name": "US Virgin Islands", "color": "#FFFFFF" },
  { "code": "AR", "name": "Argentina", "color": "#75AADB" },
  { "code": "BO", "name": "Bolivia", "color": "#FF0000" },
  { "code": "BR", "name": "Brazil", "color": "#008000" },
  { "code": "CL", "name": "Chile", "color": "#FF0000" },
  { "code": "CO", "name": "Colombia", "color": "#FFFF00" },
  { "code": "EC", "name": "Ecuador", "color": "#FFFF00" },
  { "code": "GF", "name": "French Guiana", "color": "#FFDB00" },
  { "code": "GY", "name": "Guyana", "color": "#FCF686" },
  { "code": "PY", "name": "Paraguay", "color": "#FF0000" },
  { "code": "PE", "name": "Peru", "color": "#FF0000" },
  { "code": "SR", "name": "Suriname", "color": "#FFFFFF" },
  { "code": "UY", "name": "Uruguay", "color": "#0000FF" },
  { "code": "VE", "name": "Venezuela", "color": "#FFFF00" },
  { "code": "AF", "name": "Afghanistan", "color": "#000000" },
  { "code": "AM", "name": "Armenia", "color": "#FF0000" },
  { "code": "AZ", "name": "Azerbaijan", "color": "#0000FF" },
  { "code": "BH", "name": "Bahrain", "color": "#FF0000" },
  { "code": "BD", "name": "Bangladesh", "color": "#F4263F" },
  { "code": "BT", "name": "Bhutan", "color": "#E48400" },
  { "code": "BN", "name": "Brunei", "color": "#FFFF00" },
  { "code": "KH", "name": "Cambodia", "color": "#FF0000" },
  { "code": "CN", "name": "China", "color": "#FF0000" },
  { "code": "GE", "name": "Georgia", "color": "#FF0000" },
  { "code": "HK", "name": "Hong Kong", "color": "#FF0000" },
  { "code": "IN", "name": "India", "color": "#FFA500" },
  { "code": "ID", "name": "Indonesia", "color": "#FF0000" },
  { "code": "IR", "name": "Iran", "color": "#008000" },
  { "code": "IQ", "name": "Iraq", "color": "#FF0000" },
  { "code": "IL", "name": "Israel", "color": "#0000FF" },
  { "code": "JP", "name": "Japan", "color": "#FF0000" },
  { "code": "JO", "name": "Jordan", "color": "#000000" },
  { "code": "KZ", "name": "Kazakhstan", "color": "#007FFF" },
  { "code": "KP", "name": "Korea, North", "color": "#FF0000" },
  { "code": "KR", "name": "Korea, South", "color": "#FFFFFF" },
  { "code": "KW", "name": "Kuwait", "color": "#008000" },
  { "code": "KG", "name": "Kyrgyzstan", "color": "#FF0000" },
  { "code": "LA", "name": "Laos", "color": "#FF0000" },
  { "code": "LB", "name": "Lebanon", "color": "#FF0000" },
  { "code": "MO", "name": "Macau", "color": "#008000" },
  { "code": "MY", "name": "Malaysia", "color": "#FFD700" },
  { "code": "MV", "name": "Maldives", "color": "#FF0000" },
  { "code": "MN", "name": "Mongolia", "color": "#0000FF" },
  { "code": "MM", "name": "Myanmar", "color": "#FFFF00" },
  { "code": "NP", "name": "Nepal", "color": "#DC143C" },
  { "code": "OM", "name": "Oman", "color": "#FF0000" },
  { "code": "PK", "name": "Pakistan", "color": "#006400" },
  { "code": "PS", "name": "Palestine", "color": "#000000" },
  { "code": "PH", "name": "Philippines", "color": "#0000FF" },
  { "code": "QA", "name": "Qatar", "color": "#800000" },
  { "code": "SA", "name": "Saudi Arabia", "color": "#008000" },
  { "code": "SG", "name": "Singapore", "color": "#FF0000" },
  { "code": "LK", "name": "Sri Lanka", "color": "#800000" },
  { "code": "SY", "name": "Syria", "color": "#FF0000" },
  { "code": "TW", "name": "Taiwan", "color": "#0000FF" },
  { "code": "TJ", "name": "Tajikistan", "color": "#FF0000" },
  { "code": "TH", "name": "Thailand", "color": "#FF0000" },
  { "code": "TL", "name": "Timor-Leste", "color": "#FF0000" },
  { "code": "TR", "name": "Turkey", "color": "#FF0000" },
  { "code": "TM", "name": "Turkmenistan", "color": "#008000" },
  { "code": "AE", "name": "United Arab Emirates", "color": "#FF0000" },
  { "code": "UZ", "name": "Uzbekistan", "color": "#0000FF" },
  { "code": "VN", "name": "Vietnam", "color": "#FF0000" },
  { "code": "YE", "name": "Yemen", "color": "#FF0000" },
  { "code": "AL", "name": "Albania", "color": "#FF0000" },
  { "code": "AD", "name": "Andorra", "color": "#0000FF" },
  { "code": "AT", "name": "Austria", "color": "#FF0000" },
  { "code": "BY", "name": "Belarus", "color": "#FF0000" },
  { "code": "BE", "name": "Belgium", "color": "#FF0000" },
  { "code": "BA", "name": "Bosnia and Herzegovina", "color": "#0000FF" },
  { "code": "BG", "name": "Bulgaria", "color": "#FFFFFF" },
  { "code": "HR", "name": "Croatia", "color": "#FF0000" },
  { "code": "CY", "name": "Cyprus", "color": "#0000FF" },
  { "code": "CZ", "name": "Czech Republic", "color": "#FFFFFF" },
  { "code": "DK", "name": "Denmark", "color": "#FF0000" },
  { "code": "EE", "name": "Estonia", "color": "#0000FF" },
  { "code": "FI", "name": "Finland", "color": "#FFFFFF" },
  { "code": "FR", "name": "France", "color": "#0000FF" },
  { "code": "DE", "name": "Germany", "color": "#000000" },
  { "code": "GR", "name": "Greece", "color": "#0000FF" },
  { "code": "HU", "name": "Hungary", "color": "#FF0000" },
  { "code": "IS", "name": "Iceland", "color": "#0000CC" },
  { "code": "IE", "name": "Ireland", "color": "#008000" },
  { "code": "IT", "name": "Italy", "color": "#008000" },
  { "code": "XK", "name": "Kosovo", "color": "#0000FF" },
  { "code": "LV", "name": "Latvia", "color": "#FF0000" },
  { "code": "LI", "name": "Liechtenstein", "color": "#0000FF" },
  { "code": "LT", "name": "Lithuania", "color": "#FFFF00" },
  { "code": "LU", "name": "Luxembourg", "color": "#FF0000" },
  { "code": "MT", "name": "Malta", "color": "#FF0000" },
  { "code": "MD", "name": "Moldova", "color": "#0000FF" },
  { "code": "MC", "name": "Monaco", "color": "#FF0000" },
  { "code": "ME", "name": "Montenegro", "color": "#CC0000" },
  { "code": "NL", "name": "Netherlands", "color": "#FF7F00" },
  { "code": "MK", "name": "North Macedonia", "color": "#FF0000" },
  { "code": "NO", "name": "Norway", "color": "#FF0000" },
  { "code": "PL", "name": "Poland", "color": "#FFFFFF" },
  { "code": "PT", "name": "Portugal", "color": "#008000" },
  { "code": "RO", "name": "Romania", "color": "#0000FF" },
  { "code": "RU", "name": "Russia", "color": "#FFFFFF" },
  { "code": "SM", "name": "San Marino", "color": "#FFFFFF" },
  { "code": "RS", "name": "Serbia", "color": "#FF0000" },
  { "code": "SK", "name": "Slovakia", "color": "#FFFFFF" },
  { "code": "SI", "name": "Slovenia", "color": "#FFFFFF" },
  { "code": "ES", "name": "Spain", "color": "#FF0000" },
  { "code": "SE", "name": "Sweden", "color": "#0000FF" },
  { "code": "CH", "name": "Switzerland", "color": "#FF0000" },
  { "code": "UA", "name": "Ukraine", "color": "#0000FF" },
  { "code": "GB", "name": "United Kingdom", "color": "#FF0000" },
  { "code": "AS", "name": "American Samoa", "color": "#1A63C2" },
  { "code": "AU", "name": "Australia", "color": "#008000" },
  { "code": "CK", "name": "Cook Islands", "color": "#01796F" },
  { "code": "FJ", "name": "Fiji", "color": "#75AADB" },
  { "code": "PF", "name": "French Polynesia", "color": "#FF0000" },
  { "code": "GU", "name": "Guam", "color": "#4F69C6" },
  { "code": "NC", "name": "New Caledonia", "color": "#A6AAAE" },
  { "code": "NZ", "name": "New Zealand", "color": "#000000" },
  { "code": "NU", "name": "Niue", "color": "#FFDF00" },
  { "code": "WS", "name": "Samoa", "color": "#FF0000" },
  { "code": "SB", "name": "Solomon Islands", "color": "#497E48" },
  { "code": "TO", "name": "Tonga", "color": "#FF0000" },
  { "code": "TV", "name": "Tuvalu", "color": "#76D7EA" },
  { "code": "UK", "name": "Unknown", "color": "#CCCCCC" }
];

export async function main() {
    for (const country of countries) {
        await prisma.country.upsert({
            where: { code: country.code },
            update: country,
            create: country
        });
    }
}

main()
    .then(() => prisma.$disconnect())
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });